stages:
  - test

test:
  stage: test
  script: yarn && yarn test
  environment: test
  only:
    - 01-basic-implementation
    - 02-functions-implementation
    - 04-oop-implementation
    - 05-dom-events-implementation
  tags:
    - node

variables:
  GIT_SSL_NO_VERIFY: "true"
